### ISSUE TITLE
Failed to activate the ide-flow package

### ISSUE THREAD

**Issue by bennerhq** [lukehoban/atom-ide-flow#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ide-flow](https://github.com/lukehoban/atom-ide-flow) package, v0.2.0

### Stack Trace

Failed to activate the ide-flow package

```
At Cannot read property 'check' of null

TypeError: Cannot read property 'check' of null
  at atom-workspace.<anonymous> (/Users/jbenner/.atom/packages/ide-flow/lib/ide-flow.coffee:12:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at new EditorControl (/Users/jbenner/.atom/packages/ide-flow/lib/editor-control.coffee:50:19)
  at /Users/jbenner/.atom/packages/ide-flow/lib/plugin-manager.coffee:12:39
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:266:9)
  at new PluginManager (/Users/jbenner/.atom/packages/ide-flow/lib/plugin-manager.coffee:10:43)
  at Object.module.exports.activate (/Users/jbenner/.atom/packages/ide-flow/lib/ide-flow.coffee:9:26)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  2x -6:11.3 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-seti-ui)
  2x -5:49.3 editor:newline (atom-text-editor.editor)
     -5:47.0 core:move-down (atom-text-editor.editor)
     -5:46.8 core:move-up (atom-text-editor.editor)
     -5:46.0 core:move-right (atom-text-editor.editor)
     -5:45.9 core:move-up (atom-text-editor.editor)
     -5:45.6 core:select-down (atom-text-editor.editor)
  2x -5:45.4 core:backspace (atom-text-editor.editor)
     -0:01.2 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": true
  },
  "ide-flow": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
ide-flow, v0.2.0
minimap, v4.1.4
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by forivall** [comment]
I'm having this same issue
```
❯ flow --version
Flow, a static type checker for JavaScript, version 0.8.0
```

**Comment by rainboxx** [comment]
Me too

```
⮀ flow --version
Flow, a static type checker for JavaScript, version 0.10.0
```

**Comment by rainboxx** [comment]
It seems there is an issue when activating this plugin after the startup of Atom. When the plugin is activated and Atom being restarted, the activation process succeeds.

I don't know why but `plugin-manager` is not loaded then.

**Comment by lukehoban** [comment]
I can't seem to reproduce this - is it fixed by the changes in v.0.3.0?

**Comment by tysoncadenhead** [comment]
I just got this issue for the first time today. It was working up until now.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [ide-flow](https://github.com/lukehoban/atom-ide-flow) package, v0.8.0

### Stack Trace

Failed to activate the ide-flow package

```
At Cannot read property 'check' of null

TypeError: Cannot read property 'check' of null
    at atom-workspace.<anonymous> (/Users/tysoncadenhead/.atom/packages/ide-flow/lib/ide-flow.coffee:12:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at new EditorControl (/Users/tysoncadenhead/.atom/packages/ide-flow/lib/editor-control.coffee:50:19)
    at /Users/tysoncadenhead/.atom/packages/ide-flow/lib/plugin-manager.coffee:12:39
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:290:9)
    at new PluginManager (/Users/tysoncadenhead/.atom/packages/ide-flow/lib/plugin-manager.coffee:10:43)
    at Object.module.exports.activate (/Users/tysoncadenhead/.atom/packages/ide-flow/lib/ide-flow.coffee:9:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:338:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:04.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:04.5.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-always.theme-batman-syntax.theme-seti-ui)
     -2:53.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:53.5.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-always.theme-batman-syntax.theme-seti-ui)
     -2:50.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:50.8.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-always.theme-batman-syntax.theme-seti-ui)
     -2:29.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:45.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:45.8.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-always.theme-batman-syntax.theme-seti-ui)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "flow-ide",
      "atom-alignment"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-mocha"
    ],
    "projectHome": "/Sites/aloompa",
    "themes": [
      "seti-ui",
      "batman-syntax"
    ]
  },
  "ide-flow": {
    "flowPath": "/Users/tysoncadenhead/.nvm/versions/node/v5.0.0/bin/flow"
  }
}
```

### Installed Packages

``` coffee
# User
atom-ctags, v4.4.1
atom-jshint, v2.0.0
batman-syntax, v1.0.1
compare-files, v0.6.2
esformatter, v1.16.0
ide-flow, v0.8.0
language-babel, v2.5.3
linter, v1.11.3
mixed-indent-warning, v0.2.0
react-es6-snippets, v0.2.0
seti-ui, v0.8.1

# Dev
No dev packages
```
