### ISSUE TITLE
Uncaught TypeError: Cannot read property 'check' of null

### ISSUE THREAD

**Issue by aintnorest** [lukehoban/atom-ide-flow#43]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [ide-flow](https://github.com/lukehoban/atom-ide-flow) package, v0.8.0
### Stack Trace

Uncaught TypeError: Cannot read property 'check' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:788

TypeError: Cannot read property 'check' of null
  at atom-workspace.<anonymous> (/Users/vizidrix/.atom/packages/ide-flow/lib/ide-flow.coffee:12:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at /Users/vizidrix/.atom/packages/ide-flow/lib/editor-control.coffee:31:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:519:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:529:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:512:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:560:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```
### Commands

```
     -0:13.1.0 core:move-right (atom-text-editor#ide-flow.expressionTypeInterval.editor.mini.is-focused)
  4x -0:10.5.0 core:backspace (atom-text-editor#ide-flow.expressionTypeInterval.editor.mini.is-focused)
  3x -0:06.6.0 core:save (atom-text-editor#ide-flow.expressionTypeInterval.editor.mini.is-focused)
     -0:01.2.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-elucidator.theme-seti-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "elucidator"
    ],
    "disabledPackages": [
      "autocomplete-snippets"
    ]
  },
  "ide-flow": {
    "flowPath": "/usr/local/bin/flow",
    "expressionTypeInterval": 100
  }
}
```
### Installed Packages

``` coffee
# User
block-cursor, v0.13.1
elucidator, v0.1.1
ide-flow, v0.8.0
language-babel, v0.15.12
linter, v1.9.1
linter-flow-plus, v3.1.0
minimap, v4.15.0
react, v0.12.10
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by codebreach** [comment]
bump
