### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by acarl005** [lukehoban/atom-ide-flow#56]
Really excited to use this package. Having trouble installing it though.

```sh
$ uname -a
Darwin MacBook-Pro-4.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```
```sh
$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.12.2
```
```sh
$ apm i ide-flow
Installing ide-flow to /Users/andy/.atom/packages ✗

npm ERR! git clone --template=/Users/andy/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository '/Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=/Users/andy/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Invalid username or password.
npm ERR! git clone --template=/Users/andy/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/andy/.atom/.apm/.apmrc" "--userconfig" "/Users/andy/.atom/.apmrc" "install" "/private/var/folders/cf/0cd30hsj11j9931m0mx5f7yw0000gn/T/d-117812-88013-1t5alcp.4zf0nqaor/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/andy/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository '/Users/andy/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cf/0cd30hsj11j9931m0mx5f7yw0000gn/T/apm-install-dir-117812-88013-1r9dea7.rc5vdndn29/npm-debug.log
```

Not sure why its saying `Invalid username or password`.

**Comment by mincer-ray** [comment]
having the same issue

**Comment by acarl005** [comment]
I tried manually copying this to `~/.atom/packages`, and got a similar error.

```sh
$ cd ~/.atom/packages
$ git clone https://github.com/lukehoban/atom-ide-flow.git
$ cd atom-ide-flow
```

```sh
$ npm install
npm ERR! Error while executing:
npm ERR! /usr/local/opt/git/bin/git ls-remote -h -t https://github.com/Benvie/harmony-collections.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2017-09-13T17_52_49_545Z-debug.log
```

<details><summary>Here's the NPM debug log</summary><p>

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/andy/.nvm/versions/node/v8.1.3/bin/node',
1 verbose cli   '/Users/andy/.nvm/versions/node/v8.1.3/bin/npm',
1 verbose cli   'i' ]
2 info using npm@5.3.0
3 info using node@v8.1.3
4 verbose npm-session db55ef4de53c9da0
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall ide-flow@0.8.0
7 info lifecycle ide-flow@0.8.0~preinstall: ide-flow@0.8.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 200 http://registry.npmjs.org/fuzzaldrin 255ms
15 http fetch GET 200 http://registry.npmjs.org/jquery 255ms
16 http fetch GET 200 http://registry.npmjs.org/emissary 261ms
17 silly pacote range manifest for fuzzaldrin@~2.1.0 fetched in 273ms
18 silly pacote range manifest for jquery@^2 fetched in 273ms
19 silly pacote range manifest for emissary@~1.2.1 fetched in 275ms
20 http fetch GET 200 http://registry.npmjs.org/underscore-plus 68ms
21 silly pacote range manifest for underscore-plus@1.x fetched in 71ms
22 http fetch GET 200 http://registry.npmjs.org/atom-space-pen-views 365ms
23 http fetch GET 200 http://registry.npmjs.org/property-accessors 97ms
24 silly pacote range manifest for atom-space-pen-views@^2.0.3 fetched in 381ms
25 silly pacote range manifest for fuzzaldrin@^2.1.0 fetched in 2ms
26 silly pacote range manifest for property-accessors@^1.1 fetched in 109ms
27 http fetch GET 200 http://registry.npmjs.org/mixto 126ms
28 silly pacote range manifest for mixto@1.x fetched in 129ms
29 http fetch GET 200 http://registry.npmjs.org/underscore 70ms
30 silly pacote range manifest for underscore@~1.6.0 fetched in 74ms
31 http fetch GET 200 http://registry.npmjs.org/figlet 475ms
32 silly pacote version manifest for figlet@1.0.8 fetched in 511ms
33 http fetch GET 304 http://registry.npmjs.org/es6-weak-map 119ms (from cache)
34 silly pacote range manifest for es6-weak-map@^0.1.2 fetched in 123ms
35 http fetch GET 200 http://registry.npmjs.org/optimist 104ms
36 silly pacote range manifest for optimist@~0.6.0 fetched in 108ms
37 http fetch GET 200 http://registry.npmjs.org/space-pen 211ms
38 silly pacote range manifest for space-pen@^5.1.2 fetched in 214ms
39 silly pacote version manifest for jquery@2.1.4 fetched in 4ms
40 http fetch GET 304 http://registry.npmjs.org/d 159ms (from cache)
41 http fetch GET 304 http://registry.npmjs.org/es6-symbol 160ms (from cache)
42 http fetch GET 304 http://registry.npmjs.org/es5-ext 162ms (from cache)
43 silly pacote range manifest for es5-ext@~0.10.6 fetched in 170ms
44 http fetch GET 304 http://registry.npmjs.org/es6-iterator 178ms (from cache)
45 http fetch GET 200 http://registry.npmjs.org/es6-iterator 11ms (from cache)
46 silly pacote range manifest for es6-symbol@~3.1 fetched in 11ms
47 silly pacote range manifest for d@~0.1.1 fetched in 182ms
48 silly pacote range manifest for es6-symbol@~2.0.1 fetched in 187ms
49 silly pacote range manifest for es5-ext@~0.10.14 fetched in 6ms
50 silly pacote range manifest for es5-ext@~0.10.2 fetched in 7ms
51 silly pacote range manifest for es6-iterator@2 fetched in 19ms
52 silly pacote range manifest for d@1 fetched in 8ms
53 silly pacote range manifest for es5-ext@~0.10.5 fetched in 5ms
54 silly pacote range manifest for es5-ext@^0.10.14 fetched in 2ms
55 silly pacote range manifest for es6-symbol@^3.1 fetched in 2ms
56 silly pacote range manifest for es5-ext@^0.10.9 fetched in 3ms
57 silly pacote range manifest for es6-iterator@~0.1.3 fetched in 196ms
58 http fetch GET 200 http://registry.npmjs.org/minimist 124ms
59 http fetch GET 304 http://registry.npmjs.org/wordwrap 127ms (from cache)
60 silly pacote range manifest for minimist@~0.0.1 fetched in 128ms
61 silly pacote range manifest for wordwrap@~0.0.2 fetched in 128ms
62 http fetch GET 200 http://registry.npmjs.org/grim 158ms
63 silly pacote range manifest for grim@^1.0.0 fetched in 161ms
64 silly pacote range manifest for emissary@^1.2.0 fetched in 3ms
65 silly pacote version manifest for figlet@1.0.8 fetched in 8ms
66 silly resolveWithNewModule figlet@1.0.8 checking installable status
67 silly pacote range manifest for emissary@~1.2.1 fetched in 10ms
68 silly resolveWithNewModule emissary@1.2.2 checking installable status
69 silly pacote range manifest for jquery@^2 fetched in 11ms
70 silly resolveWithNewModule jquery@2.2.4 checking installable status
71 silly pacote range manifest for fuzzaldrin@~2.1.0 fetched in 11ms
72 silly resolveWithNewModule fuzzaldrin@2.1.0 checking installable status
73 silly pacote range manifest for atom-space-pen-views@^2.0.3 fetched in 12ms
74 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
75 silly pacote range manifest for space-pen@^5.1.2 fetched in 1ms
76 silly resolveWithNewModule space-pen@5.1.2 checking installable status
77 silly pacote range manifest for grim@^1.0.0 fetched in 2ms
78 silly resolveWithNewModule grim@1.5.0 checking installable status
79 silly pacote version manifest for jquery@2.1.4 fetched in 2ms
80 silly resolveWithNewModule jquery@2.1.4 checking installable status
81 silly pacote range manifest for underscore-plus@1.x fetched in 3ms
82 silly resolveWithNewModule underscore-plus@1.6.6 checking installable status
83 silly pacote range manifest for mixto@1.x fetched in 12ms
84 silly resolveWithNewModule mixto@1.0.0 checking installable status
85 silly pacote range manifest for property-accessors@^1.1 fetched in 12ms
86 silly resolveWithNewModule property-accessors@1.1.3 checking installable status
87 silly fetchPackageMetaData error for harmony-collections@git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 Error while executing:
87 silly fetchPackageMetaData /usr/local/opt/git/bin/git ls-remote -h -t https://github.com/Benvie/harmony-collections.git
87 silly fetchPackageMetaData
87 silly fetchPackageMetaData remote: Repository not found.
87 silly fetchPackageMetaData fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
87 silly fetchPackageMetaData
87 silly fetchPackageMetaData exited with error code: 128
88 verbose stack Error: exited with error code: 128
88 verbose stack     at ChildProcess.onexit (/Users/andy/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
88 verbose stack     at emitTwo (events.js:125:13)
88 verbose stack     at ChildProcess.emit (events.js:213:7)
88 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
89 verbose cwd /Users/andy/.atom/packages/atom-ide-flow
90 verbose Darwin 15.6.0
91 verbose argv "/Users/andy/.nvm/versions/node/v8.1.3/bin/node" "/Users/andy/.nvm/versions/node/v8.1.3/bin/npm" "i"
92 verbose node v8.1.3
93 verbose npm  v5.3.0
94 error Error while executing:
94 error /usr/local/opt/git/bin/git ls-remote -h -t https://github.com/Benvie/harmony-collections.git
94 error
94 error remote: Repository not found.
94 error fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
94 error
94 error exited with error code: 128
95 verbose exit [ 1, true ]
```

</p></details>

**Comment by lnmunhoz** [comment]
Same here! + 1

**Comment by paramaggarwal** [comment]
Use `ide-flowtype` package which is the official and correct package.
