### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by cocodrino** [lukehoban/atom-ide-flow#9]
Hi..I'm constantly receiving this error...

Uncaught Error: spawn EACCES
/opt/atom/resources/app/src/workspace.js:614
Show Stack Trace

the ST
Error: spawn EACCES
  at exports._errnoException (util.js:742:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/opt/atom/resources/app/src/buffered-process.js:51:37)
  at run (/home/yo/.atom/packages/ide-flow/lib/util-flow-command.coffee:18:25)
  at Object.module.exports.startServer (/home/yo/.atom/packages/ide-flow/lib/util-flow-command.coffee:55:15)
  at Object.module.exports.check (/home/yo/.atom/packages/ide-flow/lib/util-flow-command.coffee:64:45)
  at PluginManager.check (/home/yo/.atom/packages/ide-flow/lib/plugin-manager.coffee:52:21)
  at atom-workspace.<anonymous> (/home/yo/.atom/packages/ide-flow/lib/ide-flow.coffee:12:22)
  at atom-workspace.handler (/opt/atom/resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:156:19)
  at WorkspaceView.jQuery.fn.trigger (/opt/atom/resources/app/src/space-pen-extensions.js:64:23)
  at /home/yo/.atom/packages/ide-flow/lib/editor-control.coffee:28:28
  at TextBuffer.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:973:19)
  at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/opt/atom/resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/opt/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:167:20)

I try change the file permission, but the error persist (even with other files in the same /src folder)

please let me know if you can fix it...thanks!...

**Comment by matgessel** [comment]
I get a similar error that brought me to this bug. 

Reproduction: 
1. launch Atom
2. Atom > Open Your Stylesheet
3. View > Panes > Split Right

I have the following packages installed:
* autocomplete-plus
* ide-flow
* linter
* react

**Comment by lukehoban** [comment]
This should be fixed with c4b4ead.
